### ISSUE TITLE
[Question] Any news on the Farsight issues

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-observer-tool#12]
Hey Guys, since the offsets do not work anymore and the Farsight Module does not connect: Are there any news on when the problem will be solved? Are there any status updates?

Also see here:

https://github.com/RCVolus/league-prod-toolkit/issues/288

**Comment by sdomi4** [comment]
See https://github.com/RCVolus/league-prod-toolkit/issues/311 – its taking longer than ususal due to the move to 64bit. Updates will happen as soon as they are ready.

**Comment by Freeedooo** [comment]
Thank you. I just wanted to reassure that you know about and look into the issue 😄

**Comment by Freeedooo** [comment]
In case you missed it. Maybe that will help! https://github.com/floh22/LeagueBroadcast/releases/tag/v1.7.1

**Comment by sdomi4** [comment]
Don't worry, we are well aware ;) https://github.com/floh22/native-farsight-module/pull/11
