### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by kaprixal** [RCVolus/league-observer-tool#13]
I'm trying to get the observer tool working with the prod tool-kit, but I'm running into an error while trying to connect. I've read through the Github and there doesn't seem to be any info about this, so any help would be appreciated!

![image](https://user-images.githubusercontent.com/29721326/232996781-983a2082-bb7b-4714-9983-e11b28ff50bf.png)

**Comment by sdomi4** [comment]
403 indicates that authentication is enabled. Make sure you set a working key in the observer tool config.

**Comment by kaprixal** [comment]
Yes, I've put in a working key but now I'm getting this error. It's the API key from the Riot Developer Portal Correct? I've refreshed and tried to use it multiple times but it isn't working, so any help would be appreciated!
![image](https://user-images.githubusercontent.com/29721326/233254157-86ce9c85-1742-4e12-957e-cd6ef0950c02.png)

**Comment by sdomi4** [comment]
The key is from the toolkit itself (starts with `RCVPT-`, not `RGAPI-`). You can setup keys in the toolkit or configure the admin key.

The error from the second screenshot indicates the toolkit isn't running.

**Comment by kaprixal** [comment]
Gotcha, it works now. Thank you!
