### ISSUE TITLE
Vanguard

### ISSUE THREAD

**Issue by HiImNandox** [RCVolus/league-observer-tool#132]
Hello, as of today vanguard has been implemented in lol. Are we at risk of being banned if we use this tool?

**Comment by sdomi4** [comment]
I'm not aware of vanguard being released on any live servers as of yet. As soon as vanguard is live, parts of this tool will become risky, although they haven't been clear at all in their communication of what is allowed and what isn't.

**Comment by HiImNandox** [comment]
Is there no way to contact a rioter through a ticket or something? Your application is too good to leave it like this

**Comment by sdomi4** [comment]
In the only communication we received, which contains straight up contradictory statements (https://www.riotgames.com/en/DevRel/vanguard-faq), they said they won't be answering any clarifying questions.

**Comment by HiImNandox** [comment]
They are doing the same thing as with Linux users with the Wine application. It's sad that everything goes like this.
