### ISSUE TITLE
[ISSUE] How to put new offset in the Observer Tool

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-observer-tool#15]
Not a bug put maybe more of an issue on my side. I've yet to find a way/place to update myself the offsets with the Observer Tools. I don,t know where I should put them to make the Observer works. Is it even possible or we need to wait for someone to update them in the tool or farsight github?

Example: In LeagueBroadcast, you can edit a config file with Notepad to put yourself the offsets and try them. Here, I've not found a way to do something similar.

**Comment by sdomi4** [comment]
This isn't possible at the moment and not necessarily planned. We aim to automatically set the correct offsets based on the client version to account for Tournament Realm.

We'll support updating offsets – if you have working offsets before they are published let us know and/or submit a Pull Request to Farsight.
