### ISSUE TITLE
[BUG] Total Gold not working (Displaying 0 for both team)

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-observer-tool#16]
**Describe the bug**
With Fiarsight, the total gold for each team is 0. Every other stats (towers, herald, barons, kills, etc) seems to work fine in the scoreboard

**Screenshots**
![image](https://user-images.githubusercontent.com/89284738/233790792-6597e9bf-17c2-4208-a0a5-7908d5d3baf2.png)

**Additional context**
Strange enough, the total gold seems to work with LeagueBroadcast and the offsets values seems to be the same in farsight for both project.

**Comment by Himyu** [comment]
This issue was fixed with one of the latest updates to the Observer Tool [v5.1.1](https://github.com/RCVolus/league-observer-tool/releases/tag/v5.1.1)
