### ISSUE TITLE
Farsight swapping between "Standby" and "Sync" every ~second [BUG] 

### ISSUE THREAD

**Issue by Scrambles1934** [RCVolus/league-observer-tool#17]
I've gone through as many threads as I can find and taken all the actionable steps located in them. Does farsight need to be updated?  It's the only thing left I've found that could be causing this. If I've missed something, I apologize.

**Comment by sdomi4** [comment]
Forgot to answer here; there was a hotfix on which changed offsets, should be fixed as of sunday.
