### ISSUE TITLE
[QUESTION] TR-Support?

### ISSUE THREAD

**Issue by Freeedooo** [RCVolus/league-observer-tool#18]
Is it possible to use the Tool with the Tournament Realm? I see that everything instead of "Replay" connects to the TR (even Farsight does connect) but inGame nothing happens.

**Comment by Himyu** [comment]
Yes, the tool also works in the Tournament Realm. if Replay does not connect it should not hinder any of the in-game features, since they don't rely on the replay connection.
Did you check your config file for the TR itself that replay is enabled?

**Comment by sdomi4** [comment]
Closing after inactivity.
