### ISSUE TITLE
[BUG] Closing the programm results in a Javascript error "Object has been destroyed"

### ISSUE THREAD

**Issue by JanRogge** [RCVolus/league-observer-tool#19]
**Describe the bug**
Closing the programm result in the error "TypeError: Object has been destroyed"

**To Reproduce**
1. Start League Observer Tool
2. Close Observer tool via cross in the top right

**Expected behavior**
No error is shown

**Screenshots**
![image](https://github.com/RCVolus/league-observer-tool/assets/11475491/a409b4ea-7fb6-4182-b0de-ccc2520c6357)

**System:**
 - OS: Windows 11 Home
 - Version: 22H2

**Comment by casbahcasts** [comment]
I don't know if this is just the same Erorr but I got several of these Error windows. They pop up one after the other:

Screenshot
![image](https://github.com/RCVolus/league-observer-tool/assets/139663872/48be3ad0-287f-4dca-a02b-581d72b3c959)
![image](https://github.com/RCVolus/league-observer-tool/assets/139663872/aaa8d54f-37f4-46ae-ba25-2f28b382abc0)

Same Steps as JanRogge. 

Ingame and in champ select everything works just fine. 

System:
Windows 10

**Comment by Himyu** [comment]
fixed with the newest update [v6.2.4](https://github.com/RCVolus/league-observer-tool/releases/tag/v6.2.4)
