### ISSUE TITLE
[Question] How do I send the Observer data from my PC to another PC?

### ISSUE THREAD

**Issue by casbahcasts** [RCVolus/league-observer-tool#20]
As in the question above, I want to have an observer PC with the Observer Tool running. 
The other PC has OBS and the production toolkit running.

I dont quiet get it, how I can send the Data gathered by the LOT to the prodkit PC, if it is possible?

Maybe someone can help me.

---edit:
well I guess, I am looking at it from the wrong perspective? I should connect to the Production Toolkit PC and Insert the other IP and API Key?

**Comment by sdomi4** [comment]
You just need to ensure that the production PC is reachable from the observer PC and configure the production PCs IP address in the observer tool settings (as noted in the [readme](https://github.com/RCVolus/league-observer-tool#installation)).
If production and observer PC are not in the same local network, you will need to use a VPN or similar to make the production PC reachable.
