### ISSUE TITLE
Suggestion: Add extended zoom and esports timer settings to game config setup

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-observer-tool#23]
The automatic game config setup is awesome! 
In my opinion it would be perfect with the extended zoom and esports timer settings included as a one click solution to set everything up on a brand new system.

**Comment by Himyu** [comment]
this is a good idea but I am not sure there is a setting for extended zoom you can set in the config, at least I am not aware of it. if you know we are happy to implement it. and yea the dragon timers should not be a problem

**Comment by sdomi4** [comment]
For our understanding: Do you want the tool to just drop in the config lines on a fresh system? Or have the observer tool enable Zoom/Esports timers ingame?

**Comment by figyl** [comment]
- "I am not sure there is a setting for extended zoom"
 For years now I have added the following line to input.ini "evtToggleExtendedZoom=[m]" and the following object to PersistedSettings.json (as insurance that it will actually work): {"name": "evtToggleExtendedZoom","value": "[m]"},

![image](https://github.com/RCVolus/league-observer-tool/assets/73833646/d0a28f0a-4bb3-4b01-810f-613dae29ad36)

- "Do you want the tool to just drop in the config lines on a fresh system? Or have the observer tool enable Zoom/Esports timers ingame?"
I believe having the extended zoom and esports timer be on automatically is a great idea, however I was just hyped about adding these lines to the config files automatically. Enabling them at the start of the game is already in muscle memory.

Hope this clears things up!

**Comment by Himyu** [comment]
To add the extended zoom we would add a customer key bind then? Should that be a custom definable? And why not just use the default one:  'CTRL+SHIFT+Y'?

**Comment by sdomi4** [comment]
Might depend on "upbringing", but the default around LEC is 'v' as a keybind (with fog of war cycle unbound from v)

**Comment by Himyu** [comment]
We have added the drakes to the auto-config with the newest update and will close this issue for now.
But we will consider your suggestion for adding a hotkey to unlock the zoom.
