### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by M1chal179** [RCVolus/league-observer-tool#24]
Hello iam running windows 10 and use league observer tool but sometimes it randomly crash during stream which is ba

**Comment by sdomi4** [comment]
Duplicate of #21

**Comment by M1chal179** [comment]
why u closed it ?

**Comment by sdomi4** [comment]
because we are tracking the observer tool crashes in #21

**Comment by M1chal179** [comment]
should i install now older version to not crash or ?

**Comment by M1chal179** [comment]
and last question can i get ban for using farsight ?

**Comment by sdomi4** [comment]
No, there isn't currently any older version you can install that is stable.
Currently, Farsight is allowed by Riot, but this stance might change in the future.
