### ISSUE TITLE
Error in Observer Tool

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-observer-tool#25]
I'm still having this issue when starting observer tool. 
![image](https://github.com/RCVolus/league-observer-tool/assets/104410235/2507d5de-aaa7-4ec0-bf88-1afa8bf841c7)

**Comment by MDvorky** [comment]
Do you have maybe a draft or manual to what should i put in, so it would be good?

**Comment by sdomi4** [comment]
The LiveEvents config is documented here: https://github.com/RCVolus/league-observer-tool#setting-up-liveevents-api
It might also not be happy if you have more events enabled due to other tools like LeagueBroadcast.
