### ISSUE TITLE
[BUG] Module '"@larseble/farsight"' has no exported member 'setVersion'.

### ISSUE THREAD

**Issue by JustSxm** [RCVolus/league-observer-tool#26]
**Describe the bug**
I want to help finding the reason why the Observer Tool crashes. Unfortunately, when I tried to run the application from source, there seems to be a method that I dont have.

**To Reproduce**
1. Clone league-observer-tool-codebase
2. npm i
3. npm start

**System:**
 - OS: Windows
 - Version: Current main branch in the repo

**Additional context**
electron/module/Farsight.ts:9:72 - error TS2305: Module '"@larseble/farsight"' has no exported member 'setVersion'.

import { connectToLeague, disconnectFromLeague, isReady, makeSnapshot, setVersion } from "@larseble/farsight";

**Comment by JustSxm** [comment]
The line "  export function setVersion(version: string): void" is missing in the @larseble/farsight index.d.ts when I install it, but on the repository it is there. Is there a version mismatch somehow?

**Comment by sdomi4** [comment]
Yes, this is due to a mismatch between the repo and the version published to npm. If you build from the source locally, things should work, we'll look into getting the npm version updated.

**Comment by Himyu** [comment]
this issue has bin fixed with a release for the native farsight module and an update to this repo
