### ISSUE TITLE
[ Question ] Is it possible to toggle the "sync" settings via a stream deck?

### ISSUE THREAD

**Issue by Wolfspletz** [RCVolus/league-observer-tool#266]
Just like the title says. Is it possible to toggle the "sync" settings via a stream deck. 
Its sometimes just realy impractical to tab to the program to toggle the settings so it would be nice if this was possible.

**Comment by sdomi4** [comment]
It would be possible, but is not implemented, as there is no intended usecase for toggling sync buttons throughout a stream. What scenario do you have where this is needed?

**Comment by sdomi4** [comment]
No, you just enable it once and are good to go. It's meant to say you sync the toolkit to whatever is happening in the lobby/ingame
