### ISSUE TITLE
[BUG] Nothing works with the Observer tool.

### ISSUE THREAD

**Issue by JustSxm** [RCVolus/league-observer-tool#27]
**Describe the bug**
I don't know why, but I would assume it has something to do with the new parch: Although new offsets have been published to the farsight repo, nothing works on my side except connecting to the client. The tool was not detecting champ select and in-game no information seemed to get to my prod-toolkit as everything just stayed to 0.

How can I verify that the offsets are indeed updated? 

I tried uninstalling and reinstalling the observer tool, no success. I might be doing something wrong.

**Comment by sdomi4** [comment]
The issues you describe are not related to offsets. I am unable to reproduce anything like this on a up to date install; both champ select and ingame work fine.

Please check if all of the observer tool modules are synced and green, and if the issue persists share versions, logs, and screenshots of the problem.

**Comment by JustSxm** [comment]
Something must of went wrong yesterday. I retried today and it works.
