### ISSUE TITLE
[BUG] Gold and Levels are not gathered in custom games

### ISSUE THREAD

**Issue by JustSxm** [RCVolus/league-observer-tool#28]
**Describe the bug**
When using this tool with prod-toolkit the Gold and Level leaderboard works when spectating a Ranked Game. When spectating a custom game both of those are blank.

**System:**
 - OS: Windows
 - Version: 6.7.2 (or whatever the latest which we had to manually install is)

**Comment by sdomi4** [comment]
Moving this to https://github.com/RCVolus/league-prod-toolkit/issues/538 as this is related to the toolkit itself, not the observer tool. Would you mind adding your toolkit version as well as the version of the ingame module there?
