### ISSUE TITLE
[BUG] Set up UI for cinematic/Observing function isn't working.

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-observer-tool#6]
Installed the most recent version of the League Observer Tools and the function to hide/show the overlays in-game (Setup UI for cinematic/Observing) won't do anything to the game when I click on it.

All the others options work as intended (Sync is green everywhere)

![image](https://user-images.githubusercontent.com/89284738/214137274-827d4ff1-e225-48a6-bb7a-be80bd9e5724.png)

**Comment by FireFoXz09** [comment]
There's no dumb question haha!

Yes, I tried spamming the button between the two options to see if the overlays disappears and nothing happen. Tried reinstalling it twice. Worked with an ancient version (last time I used it, it was 2 months ago tho.)

**Comment by FireFoXz09** [comment]
> Please make sure when you go to tolls -> replay you have the option for **send information activated** and also please check you have the replay API activate in the LoL Config

BINGO! I was on GET information instead. Thanks!

**Comment by Himyu** [comment]
No problem at all ^^
