### ISSUE TITLE
[BUG] Random crashes after 5.0.0 update

### ISSUE THREAD

**Issue by Coow** [RCVolus/league-observer-tool#7]
**Describe the bug**
League Observer Tool randomly crashes. Seems to occur right before a large teamfight(???) 
Tried both with and without Farsight & Live Events in different combinations, but still crashes. 
I have not tried on a replay to see if it happens at the same point each game as the games was customs games I don't have access to replays. 
No crash logs in the `main.log` file

**Expected behavior**
Not crash?

**Comment by FireFoXz09** [comment]
Same issues on my side. Tested on replays I downloaded and same random crash.

**Comment by sdomi4** [comment]
Just to confirm:
Does this happen with Farsight not enabled?
Does it always happen at the same point in the game?
Is there any relation to something happening in the game? (e.g, Turret Plates falling, Inhibs, Drakes, Barons, etc...)
