### ISSUE TITLE
[ Question ] Vanguard update announcement

### ISSUE THREAD

**Issue by Daminos2836** [RCVolus/league-observer-tool#77]
Riot has announced the addition of Vanguard to League of Legends in the 2024 season.
https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-

In addition, the League observer tool uses "Farsight" to obtain information. So I wanted to know if the Vanguard update might block some features?

**Comment by sdomi4** [comment]
It's definitely possible some features might stop working or can possibly even get you banned.
For now, Riot has not updated their policy to ban anything we do, but we suspect Vanguard will probably interfere.

We have contacted Riot in the hopes of finding out more; and will update here / in the toolkit repository once we know anything. For now, everything should work and be usable as expected, but we would not recommend using Farsight once Vanguard is required before any statement from Riot as you risk getting banned.

**Comment by Daminos2836** [comment]
Thank you for your reply. I'll wait for the 2024 LOL season to come out.

**Comment by HiImNandox** [comment]
Hello, some news with vanguard?

**Comment by sdomi4** [comment]
We have not received any updates yet - apparently this is still being discussed internally at Riot.

**Comment by HiImNandox** [comment]
I have been testing the app for a long time to be able to use it in my broadcasts on my team and with the Vanguard it has broken everything. Fck riot :C
