### ISSUE TITLE
[BUG] Cannot connect to server and LCU

### ISSUE THREAD

**Issue by MDvorky** [RCVolus/league-observer-tool#8]
Cannot open settings in the app.
When i open this app and try to connect also nothing happening
![obrázok_2023-03-17_135037634](https://user-images.githubusercontent.com/104410235/225909398-c68e2532-bb8a-4619-ae06-4b6d1d15b82f.png)

**Comment by sdomi4** [comment]
The settings should open in a file editor (standard editor set for .json files). Can you try setting a standard editor in your windows settings if there isn't one?
Do you see any error messages pop up in the observer tool when trying to connect (assuming that both the toolkit and league client are running)?

**Comment by MDvorky** [comment]
Nothing worked - still cannot open the settings. I can pair or connect but sitll i cannot run the settings. I need to open the settings to check the port for the LiveEvent Api :D

**Comment by MDvorky** [comment]
I still recieving this issue. I updated the port for the live event in LoL, even create the new folder but nothing happened 
![image](https://user-images.githubusercontent.com/104410235/227085696-2a1d1dd2-a456-4817-8451-2190d2dc5421.png)

**Comment by socktow** [comment]
same 
![image](https://user-images.githubusercontent.com/14296959/227106284-2b153c16-afc5-4d54-aa5e-0556ff11ae51.png)

**Comment by sdomi4** [comment]
> Nothing worked - still cannot open the settings. I can pair or connect but sitll i cannot run the settings. I need to open the settings to check the port for the LiveEvent Api :D

If the settings don't open from the app, you can edit them directly at `%APPDATA%\league-observer-tool\electron-cfg.json`.

As for the 403 error: Do you have authentication enabled in the toolkit? If so, you will need to [configure a key](https://github.com/RCVolus/league-prod-toolkit/wiki/2.-Using-Prod-Toolkit#observer-tool-with-authentication) in the observer tool.

**Comment by socktow** [comment]
@MDvorky u can try connect with Vmware ! i was used ip of vmware to connect and it was success

**Comment by sdomi4** [comment]
It's best if we keep this to one issue :) Closing here and tracking it in [#288](https://github.com/RCVolus/league-prod-toolkit/issues/288#issue-1636238341).

@socktow please regenerate your Riot API key, I've deleted the screenshot for now.

**Comment by KONGTINGYU** [comment]
Do you have any detailed solution steps？
